[features]
seeds = false
skip-lint = false

[programs.devnet]
claw = "QiAZtS7YfibVDTTarBM8bXfCtPFaMJ24BwSijZHg9W8"

[programs.localnet]
claw = "QiAZtS7YfibVDTTarBM8bXfCtPFaMJ24BwSijZHg9W8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000

[test.validator]
bind_address = "127.0.0.1"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
